#!/bin/bash
# /etc/init.d/piome-network

### BEGIN INIT INFO
# Provides:		piome-network
# Required-Start:	$all
# Required-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Configure piome network mesh-network pi-node
### END INIT INFO

case "$1" in
	start)
		echo "Starting piome-network"
		echo "Configuring pi-node" 

		sudo depmod -a
		sudo modprobe batman-adv

		sudo ifconfig wlan0 mtu 1528
		sudo ifconfig wlan0 down; sudo iwconfig wlan0 mode ad-hoc essid piome-network ap 02:12:34:56:78:90 channel 1
		
		sudo batctl if add wlan0
		sudo ifconfig wlan0 up
		sudo ifconfig bat0 up
		sudo ifconfig bat0 192.168.2.1
		;;

	stop)
		echo "Stopping piome-network" 
		sudo ifconfig bat0 down
		;;

	*)
		echo "Usage: /etc/init.d/piome-network start|stop"
		exit 1
		;;
esac

exit 0
