#!/bin/bash
# /etc/init.d/bat-signal-gateway

### BEGIN INIT INFO
# Provides:		bat-signal-gateway
# Required-Start:	$all
# Required-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Configure bat-signal mesh network gateway node
### END INIT INFO

case "$1" in
	start)
		echo "Starting bat-signal-gateway"
		echo "Configuring bat-signal-gateway" 

		sudo depmod -a
		sudo modprobe batman-adv

		sudo ifconfig wlan0 mtu 1532
		sudo ifconfig wlan0 down; sudo iwconfig wlan0 mode ad-hoc essid bat-signal-network ap 00:00:de:ad:be:ef channel 1
		
		sudo batctl if add wlan0
		sudo ifconfig wlan0 up
		sudo ifconfig bat0 up
		sudo ifconfig bat0 10.0.0.254
		sudo batctl gw_mode server 10mbit/5mbit
		sudo dhcpd bat0
		sudo iptables-restore < /etc/iptables.ipv4.nat
		;;

	stop)
		echo "Stopping bat-signal-gateway" 
		sudo ifconfig bat0 down
		;;

	*)
		echo "Usage: /etc/init.d/bat-signal-gateway start|stop"
		exit 1
		;;
esac

exit 0
